domstroy/urls.py
from django.contrib import admin
from django.urls import path, include
from api.routers import router
from main.views import Login, Logout
from api.mobilViewset import login as mlogin, register as mregister
from api.mobilrouter import router as mrouter
from rest_framework.documentation import include_docs_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('login/', Login, name='login'),
    path('logout/', Logout, name='logout'),
    path("mlogin/", mlogin, name="mlogin"),
    path("mregister/", mregister, name="mregister"),
    path('api/', include(router.urls)),
    path('mapi/', include(mrouter.urls)),
    path('admin/', admin.site.urls),
    path('docs/', include_docs_urls(title='API | Santexnika')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/', Products.as_view(), name='product'),
    path('ltv/', LTV.as_view(), name='ltv'),
    path('get-ltv-data/', get_ltv_data, name='get_ltv_data'),
    path('filial/', Filials.as_view(), name='filial'),
    path('saler/', Saler.as_view(), name='saler'),
    path('ombor/', Ombor.as_view(), name='ombor'),
    path('omborqabul/', OmborQabul.as_view(), name='omborqabul'),
    path('omborminus/', OmborMinus.as_view(), name='omborminus'),
    path('faktura/', Fakturas.as_view(), name='faktura'),
    # Recieve new
    path('recieve/',  Recieves.as_view(), name='recieve'),
    path('fakturatarix/', FakturaTarix.as_view(), name='fakturatarix'),
    path('warefaktura/', WareFakturas.as_view(), name='warefaktura'),
    path('warefakturatarix/', WareFakturaTarix.as_view(), name='warefakturatarix'),
    path('getfakturaitem/', GetFakturaItem, name='getfakturaitem'),
    path('datafak/', DataFak, name='datafak'),
    path('table/', Table.as_view(), name='table'),
    path('datatable/', DataTable.as_view(), name='datatable'),
    path('hodim/', Hodim.as_view(), name='hodim'),
    path('hodim_delete/<int:id>/', delete_hodim, name='hodim_delete'),
    path('debtor/', Debtors.as_view(), name='debtor'),
    path('debtorhistory/', DebtorHistory, name='debtorhistory'),
    path('deliverhistory/', DeliverHistory, name='deliverhistory'),
    path('deliver/', Delivers.as_view(), name='deliver'),
    path('faktura-yoqlama/', FakturaYoqlama.as_view(), name='faktura_yoqlama'),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile-setting/', ProfileSetting.as_view(), name='profile-setting'),
    path('sweet-alert/', SweetAlert.as_view(), name='sweet-alert'),
    path('date/', Date.as_view(), name='date'),
    path('widget/', Widget.as_view(), name='widget'),
    path('charthome/', ChartHome, name='charthome'),
    path('datahome/', DataHome, name='datahome'),
    path('dataware/', DataWare, name='dataware'),
    path('getitem/', GetItem, name='getitem'),
    path('summa/', Summa, name='summa'),
    path('filialkirim/', FilialKirim, name='filialkirim'),
    path('salerkirim/', SalerKirim, name='salerkirim'),
    # path('qol/', Qoldiq, name='qol'),
    path('nasiyatarix/', NasiyaTarix, name='nasiyatarix'),
    path('add_tolov/', add_tolov, name='add_tolov'),
    path('kurs-page/', kurs_page, name='kurs_page'),
    path('filialinfo/<int:id>/', filialinfo, name='filialinfo'),
    path('kassa/', kassa, name="kassa"),
    path('oylik-tolash', oylik_tolash, name='oylik-tolash'),
    path('chiqim-qilish', chiqim_qilish, name="chiqim_qilsih"),
    path('hodim-qarz/', hodimga_qarz, name='hodim-qarz'),
    path('hodim-qarzlari/', hodim_qarzlari, name='hodim-qarzlari'),
]

api/models.py
from django.db import models
from django.utils import timezone


class Yalpi_savdo(models.Model):
    products = models.ForeignKey("api.ProductFilial",on_delete=models.SET_NULL,null=True)
    filial = models.ForeignKey("api.Filial",on_delete=models.SET_NULL,null=True)
    total_sum = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.products} - yalpi:{self.total_sum}"
    

class Filial(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    qarz_som = models.IntegerField(default=0)
    qarz_dol = models.IntegerField(default=0)
    savdo_puli_som = models.IntegerField(default=0)
    savdo_puli_dol = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '2) Filial'


class HodimModel(models.Model):
    ism = models.CharField(max_length=50)
    familya = models.CharField(max_length=50)
    filial = models.ForeignKey(Filial, on_delete=models.SET_NULL, null=True, blank=True)
    oylik = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Hodimlar'

    def __str__(self) -> str:
        return f'{self.ism} {self.familya}'

    def toliq_ism_ol(self):
        return f'{self.ism} {self.familya}'

    
class HodimQarz(models.Model):
    hodim = models.ForeignKey(HodimModel, on_delete=models.CASCADE)
    qancha_som = models.PositiveIntegerField(default=0)
    qancha_dol = models.PositiveIntegerField(default=0)
    qaytargani_som = models.IntegerField(default=0)
    qaytargani_dol = models.IntegerField(default=0)
    izox = models.TextField(null=True, blank=True)
    qaytargandagi_izox = models.TextField(null=True, blank=True)
    tolandi = models.BooleanField(default=False)
    qachon = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.hodim.toliq_ism_ol()

    def qarzni_tekshir(self):
        
        if self.qancha_dol == self.qaytargani_dol and self.qancha_som == self.qaytargani_som:
            self.tolandi = True
            self.save()

        return 0

    class Meta:
        verbose_name_plural  = "Hodimlar qarzi"


class OylikTolov(models.Model):
    hodim = models.ForeignKey(HodimModel, on_delete=models.CASCADE)
    pul  = models.PositiveIntegerField(blank=False, null=False)
    sana = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.hodim.toliq_ism_ol()


class UserProfile(models.Model):
    staffs = [
        (1, 'director'),
        (2, 'manager'),
        (3, 'saler'),
        (4, 'warehouse')
    ]
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255, unique=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, null=True, blank=True)
    staff = models.IntegerField(choices=staffs, default=3)
    filial = models.ForeignKey(Filial, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name_plural = '1) User'


class Groups(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '3.1) Group'


class Deliver(models.Model):
    name = models.CharField(max_length=255)
    phone1 = models.CharField(max_length=13)
    phone2 = models.CharField(max_length=13, blank=True, null=True)
    som = models.IntegerField(default=0)
    dollar = models.IntegerField(default=0)
    difference = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '3.1) Deliver'


class DebtDeliver(models.Model):
    deliver = models.ForeignKey(Deliver, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    som = models.IntegerField(default=0)
    dollar = models.IntegerField(default=0)

    def __str__(self):
        return self.deliver.name

    class Meta:
        verbose_name_plural = 'Deliver Qarzi'


class DeliverPayHistory(models.Model):
    type_pay = (
        ("Naqd", "Naqd"),
        ("Plastik", "Plastik"),
        ("Pul o'tkazish", "Pul o'tkazish")
    )
    deliver = models.ForeignKey(Deliver, on_delete=models.CASCADE)
    som = models.IntegerField()
    dollar = models.IntegerField()
    turi = models.CharField(max_length=50, choices=type_pay, default="Naqd")
    date = models.DateTimeField(auto_now_add=True)

    #new
    izoh = models.TextField(null=True, blank=True)
    def __str__(self):
        return self.deliver.name

    class Meta:
        verbose_name_plural = 'Deliver Tolov Tarixi'


class ProductFilial(models.Model):
    measure = [
        ('dona', 'dona'),
        ('kg', 'kg'),
        ('litr', 'litr'),
        ('metr', 'metr')
    ]
    name = models.CharField(max_length=255)
    preparer = models.CharField(max_length=255, default="")
    som = models.IntegerField(default=0) #kelish narxi
    sotish_som = models.IntegerField(default=0) #sotish narxi
    dollar = models.IntegerField(default=0)
    sotish_dollar = models.IntegerField(default=0)
    kurs = models.IntegerField(default=0)
    barcode = models.CharField(max_length=255)
    group = models.ForeignKey(Groups, on_delete=models.CASCADE)
    measurement = models.CharField(choices=measure, default='dona', max_length=4)
    min_count = models.IntegerField(default=0)
    filial = models.ForeignKey(Filial, on_delete=models.CASCADE, related_name='filial_product')
    quantity = models.IntegerField(default=0)
    image = models.ImageField(upload_to="products/", null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = '3.1) Product Filial'


class Recieve(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    deliver = models.ForeignKey(Deliver, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    som = models.IntegerField(default=0)
    sum_sotish_som = models.IntegerField(default=0)
    dollar = models.IntegerField(default=0)
    sum_sotish_dollar = models.IntegerField(default=0)
    status = models.IntegerField(default=0)
    farq_dollar = models.IntegerField(default=0)
    farq_som = models.IntegerField(default=0)
    

    # difference = models.IntegerField(default=0)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name_plural = '4) Recieve'


class RecieveItem(models.Model):
    recieve = models.ForeignKey(Recieve, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductFilial, on_delete=models.CASCADE)
    som = models.IntegerField(default=0)
    sotish_som = models.IntegerField(default=0)
    dollar = models.IntegerField(default=0)
    sotish_dollar = models.IntegerField(default=0)
    kurs = models.IntegerField(default=0)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name_plural = '4.1) RecieveItem'


class Faktura(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    som = models.IntegerField(default=0)
    dollar = models.IntegerField(default=0)
    filial = models.ForeignKey(Filial, on_delete=models.CASCADE)
    status = models.IntegerField(default=0)
    difference_som = models.IntegerField(default=0)
    difference_dollar = models.FloatField(default=0)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name_plural = '6) Faktura'


class FakturaItem(models.Model):
    name = models.CharField(max_length=255)
    faktura = models.ForeignKey(Faktura, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductFilial, on_delete=models.CASCADE)
    group = models.ForeignKey(Groups, on_delete=models.CASCADE, blank=True, null=True)
    body_som = models.IntegerField(default=0)
    body_dollar = models.IntegerField(default=0)
    som = models.IntegerField(default=0)
    dollar = models.IntegerField(default=0)
    quantity = models.IntegerField(default=0)
    barcode = models.CharField(max_length=255)

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name_plural = '6.1) FakturaItem'


class Course(models.Model):
    som = models.IntegerField()

    def __str__(self):
        return str(self.som)

    class Meta:
        verbose_name_plural = "Dollar kursi"


class Shop(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    naqd_som = models.IntegerField(default=0) 
    naqd_dollar = models.IntegerField(default=0)
    plastik = models.FloatField(default=0)
    nasiya_som = models.IntegerField(default=0)
    nasiya_dollar = models.IntegerField(default=0)
    transfer = models.IntegerField(default=0)
    skidka_dollar = models.IntegerField(default=0)
    skidka_som = models.IntegerField(default=0)
    filial = models.ForeignKey(Filial, on_delete=models.CASCADE)
    saler = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
    
    #qarzni qaytarish sanasi
    debt_return = models.DateField(null=True, blank=True)
    
    debt_return = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name_plural = '5) Shop'


class Cart(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(ProductFilial, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField()
    total = models.IntegerField(blank=True, null=True)

    # def save(self, *args, **kwargs):
    #     self.total = int(self.quantity) * self.product.price
    #     super().save(*args, **kwargs)

    def __str__(self):
        try:
            return self.product.name
        except:

templates/fakturayoqlama.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Nasiyachi | Bordo</title>
{% endblock title %}
{% block css %}
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/forms/theme-checkbox-radio.css' %}">
    <link href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/apps/contacts.css' %}" rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL STYLES -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="{% static 'assets/css/scrollspyNav.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'plugins/animate/animate.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'plugins/sweetalerts/promise-polyfill.js' %}"></script>
    <link href="{% static 'plugins/sweetalerts/sweetalert2.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'plugins/sweetalerts/sweetalert.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/components/custom-sweetalert.css' %}" rel="stylesheet" type="text/css"/>
    <!-- END THEME GLOBAL STYLES -->
{% endblock css %}
{% block content %}
    <!--  BEGIN CONTENT AREA  -->
    <div id="content" class="main-content">
    <div class="layout-px-spacing">
        <div class="row layout-spacing layout-top-spacing" id="cancel-row">
            <div class="col-lg-12">
                <div class="widget-content searchable-container list">
                    <div class="searchable-items list">
                        <div class="items items-header-section">
                            <div class="item-content">
                                <div class="row" style="width: 100%;">
                                    <div class="col-4">
                                        <div class="">
                                            <h4>№</h4>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="">
                                            <h4>Sana</h4>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="user-location">
                                            <h4 style="margin-left: 0;">Farq summa</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% for kamomad in kamomads %}
                            <div class="items">
                                <div class="item-content">
                                    <div class="row" style="width: 100%;">
                                        <div class="col-4">
                                            <div class="user-profile">
                                                <div class="user-meta-info">
                                                    {#                                                        <p class="user-name">{{ forloop.counter }}</p>#}
                                                    <p class="user-name">{{ forloop.counter }}</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-4">
                                            <div class="user-profile">
                                                <div class="user-meta-info">
                                                    {#                                                            <p class="user-name">{{ debtor.name }}</p>#}
                                                    <p class="user-name">{{ kamomad.created_at|date:"Y-m-d" }}</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-4">
                                            <div class="user-profile">
                                                <!-- <p class="info-title">Telefon 1: </p> -->
                                                {#                                                    <p class="user-name">{{ debtor.phone1 }}</p>#}
                                                <p class="user-name">{{ kamomad.difference_sum|floatformat:"g" }} so'm</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}
    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'assets/js/apps/contact.js' %}"></script>
    <script src="{% static 'plugins/highlight/highlight.pack.js' %}"></script>
    <!-- END GLOBAL MANDATORY STYLES -->

    <!-- BEGIN THEME GLOBAL STYLE -->
    <script src="{% static 'assets/js/scrollspyNav.js' %}"></script>
    <script src="{% static 'plugins/sweetalerts/sweetalert2.min.js' %}"></script>
    <script src="{% static 'plugins/sweetalerts/custom-sweetalert.js' %}"></script>
    <!-- END THEME GLOBAL STYLE -->
{% endblock js %}

templates/hodim_qarzlari.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/table/datatable/datatables.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/table/datatable/dt-global_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/table/datatable/custom_dt_multiple_tables.css' %}">

{% endblock css %}


{% block content %}
    <!--  BEGIN MAIN CONTAINER  -->
    <!-- <div class="main-container" id="container"> -->
        <!--  BEGIN CONTENT AREA  -->
        <div id="content" class="main-content">
            <div class="layout-px-spacing">
                
                <div class="row layout-top-spacing">
                    <div class="col-xl-12 col-lg-8 col-sm-12  layout-spacing">
                        <div class="widget-content widget-content-area br-6">
                            <div class="row">
                                <div class="col-6">
                                    <h4>{{hodim.toliq_ism_ol}}</h4>
                                </div>
                            </div>
                            <div class="table-responsive mb-4 mt-4">
                                <table class="multi-table table table-hover" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th style="text-align: left;">#</th>
                                            <th style="text-align: left;">Qarz(so'm)</th>
                                            <th style="text-align: left;">Qarz($)</th>
                                            <th style="text-align: left;">Izox</th>
                                            <th style="text-align: left;">Sana</th>
                                            <th style="text-align: left;">To'lash</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for qarz in qarzlari %}
                                        <tr>
                                            <td style="text-align: left;">{{ forloop.counter}}</td>
                                            <td style="text-align: left;">{{ qarz.qancha_som }} so'm</td>
                                            <td style="text-align: left;">{{ qarz.qancha_dol }} $</td>
                                            <td style="text-align: left;">{{ qarz.izox }}</td>
                                            <td style="text-align: left;">{{ qarz.qachon }}</td>
                                            <td style="text-align: left;"><button class="btn btn-primary" data-toggle="modal" data-target="#Qarzni_olish_Modal_{{qarz.id}}">To'lash</button></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th style="text-align: left;">#</th>
                                            <th style="text-align: left;">Qarz(so'm)</th>
                                            <th style="text-align: left;">Qarz($)</th>
                                            <th style="text-align: left;">Izox</th>
                                            <th style="text-align: left;">Sana</th>
                                            <th style="text-align: left;">To'lash</th>
                                        </tr>
                                    </tfoot>
                                    
                                </table>
                               
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            
        </div>


        <!-- Qarzni olish Modal -->
        {% for qarz in hodim.hodimqarz_set.all %}
        <div class="modal fade" id="Qarzni_olish_Modal_{{qarz.id}}" tabindex="-1" aria-labelledby="Qarzni_olish_ModalLabel_{{qarz.id}}" aria-hidden="true">
            <div class="modal-dialog">
            <form action="{% url 'hodim-qarz' %}" method="POST">
                {% csrf_token %}
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="Qarzmi_olish_ModalLabel_{{qarz.id}}">Qarzni olish</h5>
                
                    </div>
                    <div class="modal-body">
                        <input class="form-control" type="number" name="qancha_som" placeholder="Qancha (so'm)"><br>
                        <input class="form-control" type="number" name="qancha_dol" placeholder="Qancha (dollar)"><br>
                        <textarea class="form-control" name="izox" id="" cols="30" rows="5" placeholder="Izox kiriting"></textarea>
                        <input type="hidden" name="qarz_id" value="{{qarz.id}}" >
                        <input type="hidden" name="hodim_id" value="{{hodim.id}}" >
                        <input type="hidden" name="uslub" value="tolash" id="">
                        
                    </div>
                    <div class="modal-footer">
                        
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Yopish</button>
                    <button type="submit" class="btn btn-primary">Saqlash</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
        {% endfor %}

    <!-- Succses Modal -->
    <div class="modal fade" id="MessageModal" data-backdrop="static" tabindex="-1" aria-labelledby="MessageModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="ChiqimModalLabel" style="color: green;"></h5>
            
                </div>
                <div class="modal-body">
                    {% for message in messages %}
                        <h4>{{message}}</h4>
                    {% endfor %}
                    
                </div>
                <div class="modal-footer">
                    
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Yopish</button>
                </div>
            </div>
        </div>
    </div>
        <!--  END CONTENT AREA  -->
    <!-- </div> -->
    <!-- END MAIN CONTAINER -->
{% endblock content %}

{% block js %}
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{% static 'plugins/table/datatable/datatables.js' %}"></script>
        <!--  BEGIN CUSTOM SCRIPTS FILE  -->
        <script src="{% static 'assets/js/scrollspyNav.js' %}"></script>

        
   <script>
        $(document).ready(function() {
            $('table.multi-table').DataTable({
                "oLanguage": {
                    "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
                    "sInfo": "Showing page _PAGE_ of _PAGES_",
                    "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                    "sSearchPlaceholder": "Search...",
                   "sLengthMenu": "Results :  _MENU_",
                },
                "stripeClasses": [],
                "lengthMenu": [7, 10, 20, 50],
                "pageLength": 7,
                drawCallback: function () {
                    $('.t-dot').tooltip({ template: '<div class="tooltip status" role="tooltip"><div class="arrow"></div><div class="tooltip-inner"></div></div>' })
                    $('.dataTables_wrapper table').removeClass('table-striped');
                }
            });
        } );
    </script>
    <!-- END PAGE LEVEL SCRIPTS -->

    {% if messages %}
    <script>
        $(document).ready(function() {
            $('#MessageModal').modal({
                show: true
            });
        });
    </script>
    {% endif %}
   
{% endblock js %}